name: Apply
on:
  push:
    branch:
    - main
jobs:
  apply:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - run: echo "Apply..."