name: Plan
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - run: echo "Plan..."